# Global settings
[build]
  # Directory to change to before starting a build
  base = "testTaskwiseUi/taskwise"

  # Build command
  command = "npm run build"

  # Directory to publish after a successful build
  publish = "build"

# Configuration for functions (optional)
[functions]
  # Directory containing Netlify Functions
  directory = "netlify/functions"

# Configuration for headers and redirects (optional)
[[headers]]
  # For all files in the /public directory, set the cache policy to 1 hour
  for = "/public/*"
    [headers.values]
      Cache-Control = "public, max-age=3600"

# Redirect from /old-page to /new-page
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301
  force = true
